### ISSUE TITLE
make compiling error:  

### ISSUE THREAD

**Issue by BassHunger** [goldblockscoin/goldblocks#2]
Error message after   make command:

make[1]: Verzeichnis „/home/.../.../goldblocks/src/leveldb“ wird betreten
/bin/sh: 1: ./build_detect_platform: Permission denied
Makefile:18: build_config.mk: Datei oder Verzeichnis nicht gefunden
make[1]: **\* Keine Regel, um „build_config.mk“ zu erstellen.  Schluss.
make[1]: Verzeichnis „/home/.../.../goldblocks/src/leveldb“ wird verlassen
Makefile:423: die Regel für Ziel „/home/.../.../goldblocks/src/leveldb/libleveldb.a“ scheiterte
make: **\* [/home/.../.../goldblocks/src/leveldb/libleveldb.a] Fehler 2

**Comment by BassHunger** [comment]
i love linux - the answer is written in the error message

build_detect_platform is a bash script file but didn't have the rights as executeable

solution:
chmod 755 src/leveldb/build_detect_platform

@dangershony can you update the rights for build_detect_platform file
thx

**Comment by dangershony** [comment]
I am not sure I have write access
