### ISSUE TITLE
MAKE compiling error due to updated boost 1.58.0

### ISSUE THREAD

**Issue by BassHunger** [goldblockscoin/goldblocks#3]
I got an error while compiling:

> Ibuild -o build/rpcrawtransaction.o src/rpcrawtransaction.cpp
> In file included from /usr/include/boost/iterator/iterator_categories.hpp:22:0,
>                  from /usr/include/boost/iterator/iterator_facade.hpp:14,
>                  from /usr/include/boost/range/iterator_range_core.hpp:27,
>                  from /usr/include/boost/range/iterator_range.hpp:13,
>                  from /usr/include/boost/assign/list_of.hpp:20,
>                  from src/rpcrawtransaction.cpp:6:
> /usr/include/boost/variant/get.hpp: In instantiation of ‘typename boost::add_reference<T>::type boost::strict_get(boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>&) [with U = const CScriptID&; T0 = CNoDestination; T1 = CKeyID; T2 = CScriptID; T3 = boost::detail::variant::void_; T4 = boost::detail::variant::void_; T5 = boost::detail::variant::void_; T6 = boost::detail::variant::void_; T7 = boost::detail::variant::void_; T8 = boost::detail::variant::void_; T9 = boost::detail::variant::void_; T10 = boost::detail::variant::void_; T11 = boost::detail::variant::void_; T12 = boost::detail::variant::void_; T13 = boost::detail::variant::void_; T14 = boost::detail::variant::void_; T15 = boost::detail::variant::void_; T16 = boost::detail::variant::void_; T17 = boost::detail::variant::void_; T18 = boost::detail::variant::void_; T19 = boost::detail::variant::void_; typename boost::add_reference<T>::type = const CScriptID&]’:
> /usr/include/boost/variant/get.hpp:284:25:   required from ‘typename boost::add_reference<T>::type boost::get(boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>&) [with U = const CScriptID&; T0 = CNoDestination; T1 = CKeyID; T2 = CScriptID; T3 = boost::detail::variant::void_; T4 = boost::detail::variant::void_; T5 = boost::detail::variant::void_; T6 = boost::detail::variant::void_; T7 = boost::detail::variant::void_; T8 = boost::detail::variant::void_; T9 = boost::detail::variant::void_; T10 = boost::detail::variant::void_; T11 = boost::detail::variant::void_; T12 = boost::detail::variant::void_; T13 = boost::detail::variant::void_; T14 = boost::detail::variant::void_; T15 = boost::detail::variant::void_; T16 = boost::detail::variant::void_; T17 = boost::detail::variant::void_; T18 = boost::detail::variant::void_; T19 = boost::detail::variant::void_; typename boost::add_reference<T>::type = const CScriptID&]’
> src/rpcrawtransaction.cpp:217:77:   required from here
> /usr/include/boost/variant/get.hpp:178:5: error: invalid application of ‘sizeof’ to incomplete type ‘boost::STATIC_ASSERTION_FAILURE<false>’
>      BOOST_STATIC_ASSERT_MSG(
>      ^
> Makefile:2922: die Regel für Ziel „build/rpcrawtransaction.o“ scheiterte
> make: **\* [build/rpcrawtransaction.o] Fehler 1

dpkg -S /usr/include/boost/version.hpp

tells me i have
libboost1.58-dev:amd64: /usr/include/boost/version.hpp

**Comment by BassHunger** [comment]
found the same problem like in [https://github.com/vertcoin/vertcoin/issues/49]
Perhaps this is something to consider for supporting newer boost versions?"
See [http://www.reddit.com/r/vertcoin/comments/372ydk/wallet_crashes_on_os_x_1075/crjk8gs] and [https://github.com/bitcoin/bitcoin/pull/6114/files]

possible solution for Goldblocks is to change line 217
from                 const CScriptID& hash = boost::get<const CScriptID&>(address);
to
                const CScriptID& hash = boost::get(address);

but then I get error:

> Ibuild -o build/rpcrawtransaction.o src/rpcrawtransaction.cpp
> src/rpcrawtransaction.cpp: In function ‘json_spirit::Value listunspent(const Array&, bool)’:
> src/rpcrawtransaction.cpp:217:59: error: no matching function for call to ‘get(CTxDestination&)’
>                  const CScriptID& hash = boost::get(address);
>                                                            ^
> In file included from /usr/include/boost/tuple/tuple.hpp:28:0,
>                  from /usr/include/boost/assign/list_of.hpp:22,
>                  from src/rpcrawtransaction.cpp:6:
> /usr/include/boost/tuple/detail/tuple_basic.hpp:230:1: note: candidate: template<int N, class HT, class TT> typename boost::tuples::access_traits<typename boost::tuples::element<N, boost::tuples::cons<HT, TT> >::type>::const_type boost::tuples::get(const boost::tuples::cons<HT, TT>&)
>  get(const cons<HT, TT>& c) {
>  ^
> /usr/include/boost/tuple/detail/tuple_basic.hpp:230:1: note:   template argument deduction/substitution failed:
> src/rpcrawtransaction.cpp:217:59: note:   ‘CTxDestination {aka boost::variant<CNoDestination, CKeyID, CScriptID>}’ is not derived from ‘const boost::tuples::cons<HT, TT>’
>                  const CScriptID& hash = boost::get(address);
>                                                            ^
> In file included from /usr/include/boost/tuple/tuple.hpp:28:0,
>                  from /usr/include/boost/assign/list_of.hpp:22,
>                  from src/rpcrawtransaction.cpp:6:
> /usr/include/boost/tuple/detail/tuple_basic.hpp:216:1: note: candidate: template<int N, class HT, class TT> typename boost::tuples::access_traits<typename boost::tuples::element<N, boost::tuples::cons<HT, TT> >::type>::non_const_type boost::tuples::get(boost::tuples::cons<HT, TT>&)
>  get(cons<HT, TT>& c) {
>  ^
> /usr/include/boost/tuple/detail/tuple_basic.hpp:216:1: note:   template argument deduction/substitution failed:
> src/rpcrawtransaction.cpp:217:59: note:   ‘CTxDestination {aka boost::variant<CNoDestination, CKeyID, CScriptID>}’ is not derived from ‘boost::tuples::cons<HT, TT>’
>                  const CScriptID& hash = boost::get(address);
>                                                            ^
> In file included from /usr/include/boost/variant.hpp:22:0,
>                  from src/script.h:15,
>                  from src/base58.h:24,
>                  from src/rpcrawtransaction.cpp:8:
> /usr/include/boost/variant/get.hpp:245:1: note: candidate: template<class U, class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19> typename boost::add_pointer<T>::type boost::get(boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>_)
>  get(
>  ^
> /usr/include/boost/variant/get.hpp:245:1: note:   template argument deduction/substitution failed:
> src/rpcrawtransaction.cpp:217:59: note:   mismatched types ‘boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>_’ and ‘boost::variant<CNoDestination, CKeyID, CScriptID>’
>                  const CScriptID& hash = boost::get(address);
>                                                            ^
> In file included from /usr/include/boost/variant.hpp:22:0,
>                  from src/script.h:15,
>                  from src/base58.h:24,
>                  from src/rpcrawtransaction.cpp:8:
> /usr/include/boost/variant/get.hpp:261:1: note: candidate: template<class U, class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19> typename boost::add_pointer<const U>::type boost::get(const boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>_)
>  get(
>  ^
> /usr/include/boost/variant/get.hpp:261:1: note:   template argument deduction/substitution failed:
> src/rpcrawtransaction.cpp:217:59: note:   mismatched types ‘const boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>_’ and ‘boost::variant<CNoDestination, CKeyID, CScriptID>’
>                  const CScriptID& hash = boost::get(address);
>                                                            ^
> In file included from /usr/include/boost/variant.hpp:22:0,
>                  from src/script.h:15,
>                  from src/base58.h:24,
>                  from src/rpcrawtransaction.cpp:8:
> /usr/include/boost/variant/get.hpp:276:1: note: candidate: template<class U, class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19> typename boost::add_reference<T>::type boost::get(boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>&)
>  get(
>  ^
> /usr/include/boost/variant/get.hpp:276:1: note:   template argument deduction/substitution failed:
> src/rpcrawtransaction.cpp:217:59: note:   couldn't deduce template parameter ‘U’
>                  const CScriptID& hash = boost::get(address);
>                                                            ^
> In file included from /usr/include/boost/variant.hpp:22:0,
>                  from src/script.h:15,
>                  from src/base58.h:24,
>                  from src/rpcrawtransaction.cpp:8:
> /usr/include/boost/variant/get.hpp:291:1: note: candidate: template<class U, class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15, class T16, class T17, class T18, class T19> typename boost::add_reference<const U>::type boost::get(const boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>&)
>  get(
>  ^
> /usr/include/boost/variant/get.hpp:291:1: note:   template argument deduction/substitution failed:
> src/rpcrawtransaction.cpp:217:59: note:   couldn't deduce template parameter ‘U’
>                  const CScriptID& hash = boost::get(address);
>                                                            ^
> In file included from /usr/include/boost/optional.hpp:15:0,
>                  from /usr/include/boost/signals2/detail/slot_groups.hpp:15,
>                  from /usr/include/boost/signals2/signal.hpp:28,
>                  from src/keystore.h:10,
>                  from src/script.h:17,
>                  from src/base58.h:24,
>                  from src/rpcrawtransaction.cpp:8:
> /usr/include/boost/optional/optional.hpp:1184:1: note: candidate: template<class T> typename boost::optional<T>::reference_const_type boost::get(const boost::optional<T>&)
>  get ( optional<T> const& opt )
>  ^
> /usr/include/boost/optional/optional.hpp:1184:1: note:   template argument deduction/substitution failed:
> src/rpcrawtransaction.cpp:217:59: note:   ‘CTxDestination {aka boost::variant<CNoDestination, CKeyID, CScriptID>}’ is not derived from ‘const boost::optional<T>’
>                  const CScriptID& hash = boost::get(address);
>                                                            ^
> In file included from /usr/include/boost/optional.hpp:15:0,
>                  from /usr/include/boost/signals2/detail/slot_groups.hpp:15,
>                  from /usr/include/boost/signals2/signal.hpp:28,
>                  from src/keystore.h:10,
>                  from src/script.h:17,
>                  from src/base58.h:24,
>                  from src/rpcrawtransaction.cpp:8:
> /usr/include/boost/optional/optional.hpp:1192:1: note: candidate: template<class T> typename boost::optional<T>::reference_type boost::get(boost::optional<T>&)
>  get ( optional<T>& opt )
>  ^
> /usr/include/boost/optional/optional.hpp:1192:1: note:   template argument deduction/substitution failed:
> src/rpcrawtransaction.cpp:217:59: note:   ‘CTxDestination {aka boost::variant<CNoDestination, CKeyID, CScriptID>}’ is not derived from ‘boost::optional<T>’
>                  const CScriptID& hash = boost::get(address);
>                                                            ^
> In file included from /usr/include/boost/optional.hpp:15:0,
>                  from /usr/include/boost/signals2/detail/slot_groups.hpp:15,
>                  from /usr/include/boost/signals2/signal.hpp:28,
>                  from src/keystore.h:10,
>                  from src/script.h:17,
>                  from src/base58.h:24,
>                  from src/rpcrawtransaction.cpp:8:
> /usr/include/boost/optional/optional.hpp:1202:1: note: candidate: template<class T> typename boost::optional<T>::pointer_const_type boost::get(const boost::optional<T>_)
>  get ( optional<T> const_ opt )
>  ^
> /usr/include/boost/optional/optional.hpp:1202:1: note:   template argument deduction/substitution failed:
> src/rpcrawtransaction.cpp:217:59: note:   mismatched types ‘const boost::optional<T>_’ and ‘boost::variant<CNoDestination, CKeyID, CScriptID>’
>                  const CScriptID& hash = boost::get(address);
>                                                            ^
> In file included from /usr/include/boost/optional.hpp:15:0,
>                  from /usr/include/boost/signals2/detail/slot_groups.hpp:15,
>                  from /usr/include/boost/signals2/signal.hpp:28,
>                  from src/keystore.h:10,
>                  from src/script.h:17,
>                  from src/base58.h:24,
>                  from src/rpcrawtransaction.cpp:8:
> /usr/include/boost/optional/optional.hpp:1210:1: note: candidate: template<class T> typename boost::optional<T>::pointer_type boost::get(boost::optional<T>_)
>  get ( optional<T>\* opt )
>  ^
> /usr/include/boost/optional/optional.hpp:1210:1: note:   template argument deduction/substitution failed:
> src/rpcrawtransaction.cpp:217:59: note:   mismatched types ‘boost::optional<T>_’ and ‘boost::variant<CNoDestination, CKeyID, CScriptID>’
>                  const CScriptID& hash = boost::get(address);
>                                                            ^
> Makefile:2922: die Regel für Ziel „build/rpcrawtransaction.o“ scheiterte
> make: *_\* [build/rpcrawtransaction.o] Fehler 1

what to do next?

**Comment by CarloWood** [comment]
I think you need to #include <boost/variant/get.hpp>
